const PoliticaPrivacidade = () => {
  return (
    <section>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid asperiores cum harum facilis est soluta debitis, natus reprehenderit alias officiis eveniet, sapiente repudiandae illo esse? Eius alias rem veniam velit.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis ducimus itaque, tempora corporis facilis deleniti? Eos voluptas eaque, distinctio a sequi suscipit nisi alias temporibus molestias ex autem reiciendis delectus nam ab labore ipsam sunt similique. Soluta nemo fugiat consequuntur repellat, qui laboriosam exercitationem sunt veniam ullam porro, debitis quibusdam, doloribus aliquid eaque deleniti! Illo, error! Officiis qui atque quis! Eum dolores adipisci odit aliquam facere voluptates minima illum ullam repudiandae veniam facilis, voluptatibus modi soluta rem nisi tempore quas est omnis aut dolorem? Tempore sapiente architecto quas ipsa ratione ipsam perspiciatis dicta optio cumque. Eos non atque quos dolore numquam sunt voluptate ullam, quod odio eaque vel odit magni id tempore labore nulla ducimus esse eligendi asperiores? Cupiditate reiciendis ea illum optio nemo accusantium! Sit, obcaecati sint. Laborum voluptate, velit facilis voluptatum eius repudiandae iure at rem adipisci a in magni modi neque perspiciatis deleniti sequi aliquid labore aperiam voluptates blanditiis sint impedit doloremque explicabo sed. Nisi incidunt asperiores cum expedita animi earum amet, libero optio debitis cupiditate provident nihil alias ducimus eum rem praesentium quidem deserunt aliquid. Commodi facilis molestias, officiis aliquid nesciunt autem distinctio? Repellendus sed ratione eveniet sint, cupiditate quod reprehenderit explicabo earum dignissimos voluptatum unde impedit adipisci corrupti quasi aliquam qui laborum quisquam. Eaque nihil iusto architecto, at iste asperiores nostrum aperiam molestias animi est, ratione mollitia ipsa dolores repellendus repudiandae sint eligendi in saepe ullam reprehenderit quis modi hic quam quas. Asperiores nam neque totam assumenda quia! A debitis saepe accusantium veniam quisquam expedita illo iure assumenda dolore neque, ipsam ratione eos quos numquam magni ab ex, similique deleniti tempora impedit. Vero consectetur hic dolorum, minima facere rerum odit nam quod vitae voluptas! Dolorem aspernatur earum sit eligendi! Quasi, accusamus dolor. Cumque sunt nesciunt exercitationem aliquid quo veniam, eius beatae optio quam. Suscipit, eveniet.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque totam dolores aut incidunt eos ipsum exercitationem magnam? Facere modi, odio non facilis illo qui molestiae sapiente eum laudantium iure accusamus adipisci architecto, nisi quibusdam sunt vel quisquam similique voluptates. Quo ipsa tempore, tenetur natus quaerat ullam laboriosam mollitia minima distinctio consequatur odio laudantium provident earum repellendus explicabo quibusdam nobis, accusamus ducimus, minus odit sit? Vitae, accusamus amet quidem, necessitatibus enim, temporibus ab possimus omnis aperiam totam repudiandae quod illum culpa repellendus voluptas nam nostrum. Iure illum quae vel laboriosam delectus perspiciatis neque quaerat minus quo nam ad, deleniti voluptate aliquid?</p>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corporis quia obcaecati neque ab error minima repellendus perspiciatis, sit nesciunt, ipsa, nam veritatis vel accusamus enim veniam animi earum velit. Reprehenderit at laudantium placeat sit quod aspernatur dolorem natus eveniet sint deserunt quibusdam, numquam incidunt similique ad ut quaerat alias perspiciatis tempore iure modi quo dolorum explicabo dicta praesentium? Expedita aut soluta neque impedit tempore blanditiis id possimus optio accusamus modi eius, perferendis dolorem beatae magnam illo dolores! Magnam, unde natus nemo perspiciatis assumenda at nihil est. Dolorum commodi iure molestias ut natus quod adipisci, vel fugit voluptatum laboriosam culpa non ducimus rerum qui alias nostrum a, debitis quaerat, rem mollitia accusamus quam omnis! Quasi voluptatibus commodi, tempora nisi reiciendis itaque, ipsa consectetur earum eum totam quidem alias ullam nobis. Molestiae corrupti fugit enim porro ea minus, quasi corporis pariatur vero facere blanditiis, accusantium aliquam quo ab dolores tenetur quam veniam sunt laboriosam tempora nemo. Commodi maiores omnis saepe beatae iste vero animi, laudantium atque. Incidunt, totam deleniti quae aperiam placeat dolores sed ducimus velit quibusdam nihil vero saepe magnam aliquam illo nisi provident pariatur non, repudiandae expedita, accusantium maxime libero. Eligendi, laboriosam ratione culpa aspernatur natus ad iure sit accusantium.</p>
    </section>
  )
}

export default PoliticaPrivacidade
